# Default settings reference
# see: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
#
# About workaround putting this file in ~/.config/lazygit/config.yml:
# see: https://github.com/jesseduffield/lazygit/issues/1669

gui:
  sidePanelWidth: 0.2
  mainPanelSplitMode: 'horizontal' # horizontal, vertical, flexible
  enlargedSideViewLocation: top
  nerdFontsVersion: '3'
  timeFormat: "2006-01-02 15:04:05"
  shortTimeFormat: "2006-01-02 15:04:05"
  screenMode: 'half'
  filterMode: 'fuzzy'
  # Config relating to colors and styles.
  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#color-attributes
  theme:
    activeBorderColor:
      - "#5fff01"
      - "bold"
    inactiveBorderColor:
      - "#949494"
    searchingActiveBorderColor:
      - "#5fff01"
      - "bold"
    optionsTextColor:
      - "#ffaf00"
    selectedLineBgColor:
      - "#4e4e4e"
    cherryPickedCommitFgColor:
      - "#62d8f1"
    cherryPickedCommitBgColor:
      - "#d75fff"
    markedBaseCommitFgColor:
      - "#5fff01"
    markedBaseCommitBgColor:
      - "#ffd700"
    unstagedChangesColor:
      - "#ff0000"
    defaultFgColor:
      - "#ffffff"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --side-by-side
    useConfig: false
  parseEmoji: true
  log:
    showWholeGraph: true
