# -------------------------------------------------------------------------------
# Alacritty has some "features" that are ... "interesting".
# This configuration removes related keybindings and disables these "features".

[general]
live_config_reload = true
working_directory = "None"
ipc_socket = true


# ======================
# Window Settings
# ======================
[window]
option_as_alt = "Both"
decorations = "none"
opacity = 1
blur = false
padding = { x = 5, y = 5 }

# ======================
# Font Settings
# ======================
[font]
size = 14.0
normal = { family = "Hack Nerd Font Mono" }

# ======================
# Cursor Settings
# ======================
[cursor]
blink_interval = 250
style = { blinking = "Always", shape = "Block" }
vi_mode_style = { shape = "Beam" }

# ======================
# Keyboard Settings
# ======================
[keyboard]
bindings = [

    # scrollback
    { key = "PageUp", mods = "Shift", mode = "~Alt", action = "ReceiveChar" },
    { key = "PageDown", mods = "Shift", mode = "~Alt", action = "ReceiveChar" },
    { key = "Home", mods = "Shift", mode = "~Alt", action = "ReceiveChar" },
    { key = "End", mods = "Shift", mode = "~Alt", action = "ReceiveChar" },
    { key = "K", mods = "Command", mode = "~Vi|~Search", action = "ReceiveChar" },

    # searching
    { key = "F", mods = "Control|Shift", mode = "~Search", action = "ReceiveChar" },
    { key = "F", mods = "Command", mode = "~Search", action = "ReceiveChar" },
    { key = "B", mods = "Control|Shift", mode = "~Search", action = "ReceiveChar" },
    { key = "B", mods = "Command", mode = "~Search", action = "ReceiveChar" },

    # copy/paste
    { key = "Paste", action = "ReceiveChar" },
    { key = "Copy", action = "ReceiveChar" },
    { key = "V", mods = "Control|Shift", mode = "~Vi", action = "ReceiveChar" },
    { key = "V", mods = "Command", action = "ReceiveChar" },
    { key = "C", mods = "Control|Shift", action = "ReceiveChar" },
    { key = "C", mods = "Command", action = "ReceiveChar" },
    { key = "C", mods = "Control|Shift", mode = "Vi|~Search", action = "ReceiveChar" },
    { key = "C", mods = "Command", mode = "Vi|~Search", action = "ReceiveChar" },
    { key = "Insert", mods = "Shift", action = "ReceiveChar" },

    # fix: cannot use ctrl+/
    # https://github.com/alacritty/alacritty/issues/3586
    { key = "Slash", mods = "Control", chars = "\u001f" },

    # opacity controls
    # TODO: improve command, and implement increment/decrement, when get-config becomes officially available
    { key = "F1", mods = "Shift", command = { program = "/opt/homebrew/bin/alacritty", args = ["msg", "config", "-w=-1", "window.opacity=1.0"] } },
    { key = "F2", mods = "Shift", command = { program = "/opt/homebrew/bin/alacritty", args = ["msg", "config", "-w=-1", "window.opacity=0.7"] } },

    # TODO: alacritty custom key bindings
    # { key = "K", mods = "Shift|Option", action = "IncreaseFontSize" },
    # { key = "J", mods = "Shift|Option", action = "DecreaseFontSize" },
    # { key = "H", mods = "Shift|Option", action = "ResetFontSize" },
    # { key = "K", mods = "Command", action = "ClearHistory" },  # Cmd+K to clear scrollback
    # { key = "V", mods = "Super", action = "ToggleViMode" },
    # { key = "C", mods = "Super", action = "ClearLogNotice" },

]

# ======================
# Mouse Settings
# ======================
[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Right", action = "ReceiveChar" }
]

[scrolling]
history = 0

[selection]
save_to_clipboard = false

# ======================
# Colors
# ======================
[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

# ======================
# Colors (monokai)
# ======================

[colors.primary]
background = "#272822"
foreground = "#f8f8f2"

[colors.cursor]
text = "#272822"
cursor = "#f8f8f2"

[colors.normal]
black = "#272822"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f8f8f2"

[colors.bright]
black = "#75715e"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f9f8f5"
