-- https://github.com/mason-org/mason.nvim

return {
  {
    "mason-org/mason.nvim",
    opts = {
      ui = {
        border = "rounded",
      },
      -- https://www.lazyvim.org/plugins/lsp#masonnvim-1
      ensure_installed = {
        "awk-language-server",
        "bash-language-server",
        "buf",
        "buf-language-server",
        "clangd",
        "cmakelang",
        "cmakelint",
        "codelldb",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "editorconfig-checker",
        "eslint-lsp",
        "fixjson",
        "flake8",
        "gh",
        "gofumpt",
        "goimports",
        "gopls",
        "hadolint",
        "jq",
        "jq-lsp",
        "json-lsp",
        "jsonlint",
        "lua-language-server",
        "markdown-toc",
        "markdownlint-cli2",
        "marksman",
        "neocmakelsp",
        "pylint",
        "pyright",
        "ruff",
        "semgrep",
        "shellcheck",
        "shfmt",
        "solidity",
        "sqlfluff",
        "stylua",
        "taplo",
        "typescript-language-server",
        "vtsls",
        "yaml-language-server",
        "yamlfmt",
        "yamllint",
        "yq",
      },
    },
  },
}
