-- https://www.lazyvim.org/extras/util/rest#nvim-treesitter

return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cmake",
      "comment",
      "cpp",
      "css",
      "devicetree",
      "diff",
      "dockerfile",
      "editorconfig",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "go",
      "gpg",
      "graphql",
      "html",
      "http",
      "javascript",
      "jq",
      "jsdoc",
      "json",
      "lua",
      "luadoc",
      "nu",
      "printf",
      "proto",
      "python",
      "regex",
      "rust",
      "solidity",
      "sql",
      "ssh_config",
      "tmux",
      "toml",
      "typescript",
      "xml",
      "yaml",
    },
  },
}
