# https://yazi-rs.github.io/docs/configuration/keymap
[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

[[mgr.prepend_keymap]]
on = "<C-y>"
run = ["plugin system-clipboard"]
desc = "Copy contents of file"

[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on = "<A-y>"
run = ["plugin copy-file-contents"]
desc = "Copy contents of file"

[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "H"
run = "plugin duckdb -1"
desc = "Scroll one column to the left"

[[mgr.prepend_keymap]]
on = "L"
run = "plugin duckdb +1"
desc = "Scroll one column to the right"

[[mgr.prepend_keymap]]
on = ["g", "o"]
run = "plugin duckdb -open"
desc = "open with duckdb"

[[mgr.prepend_keymap]]
on = ["g", "u"]
run = "plugin duckdb -ui"
desc = "open with duckdb ui"

[[mgr.prepend_keymap]]
on   = [ "t", "h" ]
run  = "plugin toggle-pane min-parent"
desc = "Toggle Parent Pane"

[[mgr.prepend_keymap]]
on   = [ "t", "j" ]
run  = "plugin toggle-pane min-current"
desc = "Toggle Current Pane"

[[mgr.prepend_keymap]]
on   = [ "t", "k" ]
run  = "plugin toggle-pane min-current"
desc = "Toggle Preview Pane"

[[mgr.prepend_keymap]]
on   = [ "t", "l" ]
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[mgr.prepend_keymap]]
on   = [ "t", "t" ]
run  = "plugin toggle-pane reset"
desc = "Reset pane size"

[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on = [ "P", "s" ]
run = "plugin projects save"
desc = "Save current project"

[[mgr.prepend_keymap]]
on = [ "P", "l" ]
run = "plugin projects load"
desc = "Load project"

[[mgr.prepend_keymap]]
on = [ "P", "P" ]
run = "plugin projects load_last"
desc = "Load last project"

[[mgr.prepend_keymap]]
on = [ "P", "d" ]
run = "plugin projects delete"
desc = "Delete project"

[[mgr.prepend_keymap]]
on = [ "P", "D" ]
run = "plugin projects delete_all"
desc = "Delete all projects"

[[mgr.prepend_keymap]]
on = [ "P", "m" ]
run = "plugin projects 'merge current'"
desc = "Merge current tab to other projects"

[[mgr.prepend_keymap]]
on = [ "P", "M" ]
run = "plugin projects 'merge all'"
desc = "Merge current project to other projects"

[[mgr.prepend_keymap]]
on = [ "q" ]
run = "plugin projects quit"
desc = "Save last project and exit the process"

[[mgr.prepend_keymap]]
on   = "f"
run  = "plugin jump-to-char"
desc = "Jump to char"

[[mgr.prepend_keymap]]
on = [ "M" ]
run = "plugin relative-motions"
desc = "Trigger a new relative motion"

[[mgr.prepend_keymap]]
on = "<C-p>"
run = 'shell -- qlmanage -p "$@"'
desc = "Quick Look (MacOS)"

[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "Go to root (current repo)"

[[mgr.prepend_keymap]]
on = [ "g", "l" ]
run = 'shell -- ya emit cd "~/Library/Application Support/"'
desc = "Go ~/Library/Application Support/"

[[mgr.prepend_keymap]]
on = [ "g", "s" ]
run = 'shell -- ya emit cd "~/.local/share"'
desc = "Go ~/.local/share"

[[mgr.prepend_keymap]]
on = [ "g", "c" ]
run = 'shell -- ya emit cd $(chezmoi source-path 2>/dev/null || echo .)'
desc = "chezmoi cd"

[[mgr.prepend_keymap]]
on = [ "g", "z" ]
run = 'shell -- ya emit cd $(zoxide query zmk config 2>/dev/null || echo .)'
desc = "z zmk config"

[[mgr.prepend_keymap]]
on = [ "g", "k" ]
run = 'shell -- ya emit cd "~/Desktop/"'
desc = "Go ~/Desktop"

[[mgr.prepend_keymap]]
on = [ "g", "e" ]
run = 'shell --interactive -- ya emit cd $(zoxide query)"'
desc = "Go ..."

[[mgr.prepend_keymap]]
on   = [ "c", "a", "a" ]
run  = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "p" ]
run  = "plugin compress -p"
desc = "Archive selected files (password)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "h" ]
run  = "plugin compress -ph"
desc = "Archive selected files (password+header)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "l" ]
run  = "plugin compress -l"
desc = "Archive selected files (compression level)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "u" ]
run  = "plugin compress -phl"
desc = "Archive selected files (password+header+level)"

[[mgr.prepend_keymap]]
on   = "<C-d>"
run  = "plugin diff"
desc = "Diff the selected with the hovered file"
