#!/usr/bin/env bash

# routine
[ ! -f script/helper ] && echo "Please run this from $HOME/.dotfiles" && exit 1
. script/helper

set -e

# If we're on a Mac, let's install and setup homebrew.
if test "$(uname)" = "Darwin"
then
  info "Checking Homebrew..."
  if source "$DOTFILES/homebrew/brew.sh" # | while read -r data; do info "$data"; done
  then
    success "Homebrew installed"
  else
    fail "Error installing/updating Homebrew"
  fi
fi
